### ISSUE TITLE
POST request API for new arrangement

### ISSUE THREAD

**Issue by Jeffchiucp** [arrangement-io/arrangethat-io-server#19]
https://github.com/arrangement-io/arrangethat-io-server/blob/5cf927da234b08132d42ce5d88ff053d1a515c03/app.py#L94-L110

Second api is to create a new arrangement on backend side. 
It will be the POST request from the backend

**Comment by deonjo** [comment]
Yes sounds good.


On December 13, 2018 at 7:39:38 PM, Jeff Chiu (notifications@github.com)
wrote:

https://github.com/arrangement-io/arrangethat-io-server/blob/5cf927da234b08132d42ce5d88ff053d1a515c03/app.py#L94-L110

Second api is to create a new arrangement on backend side.
It will be the POST request from the backend

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/arrangement-io/arrangethat-io-server/issues/19>, or mute
the thread
